### ISSUE TITLE
Missing Entries in 49-2/AerodromePresentOrForecastWeather

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm-codelists#2]
The following weather phenomena contractions are missing in the 49-2/AerodromePresentOrForecastWeather table. WMO 306 Table 4678 allows these types to appear the METAR/SPECI and TAF code forms:

-SS
-DS
+FC

Ref  15.8.4 Intensity shall be indicated only with precipitation, precipitation associated with
showers and/or thunderstorms, funnel cloud, duststorm or sandstorm.

**Comment by blchoy** [comment]
Interestingly, all of them can be found under codes.wmo.int/306/4678, viz:

[-SS](http://codes.wmo.int/306/4678/-SS)
[-DS](http://codes.wmo.int/306/4678/-DS)
[+FC](http://codes.wmo.int/306/4678/+FC)

Apparently there are missing aliases under http://codes.wmo.int/49-2/AerodromePresentOrForecastWeather to these items in http://codes.wmo.int/306/4678.
