### ISSUE TITLE
Changes to Space Weather Containers

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm-codelists#3]
For your consideration:

* With Amendment 79 in effect, the containers "Space Wx Phenomena" and "Space Wx Locations" and the concepts therein should no longer be considered 'experimental' but 'stable'.  Status cannot be changed with Turtle files.
* Introduced a change to the Space Wx Location concepts to include the values of the latitude bands.

**Comment by amilan17** [comment]
[http://codes.wmo.int/49-2/_SpaceWxLocation](http://codes.wmo.int/49-2/_SpaceWxLocation)

http://codes.wmo.int/49-2/_SpaceWxPhenomena
